"""empty message

Revision ID: bee8eb705511
Revises: 
Create Date: 2022-02-14 22:39:06.391283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee8eb705511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_subject'), 'meeting', ['subject'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_email'), 'participant', ['email'], unique=True)
    op.create_index(op.f('ix_participant_name'), 'participant', ['name'], unique=False)
    op.create_table('meeting_participant_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_participant_role_name'), 'meeting_participant_role', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_participant_role_name'), table_name='meeting_participant_role')
    op.drop_table('meeting_participant_role')
    op.drop_index(op.f('ix_participant_name'), table_name='participant')
    op.drop_index(op.f('ix_participant_email'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_meeting_subject'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
